name: Backup and Maintenance

on:
  schedule:
    - cron: '0 2 * * *'  # Daily at 2 AM
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Backup Database and Media
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/beb/PycharmProjects/watermarking
            
            # Create backup directory with timestamp
            BACKUP_DIR="backups/prod_backup_$(date +%Y%m%d_%H%M%S)"
            mkdir -p "$BACKUP_DIR"
            
            echo "🗄️ Creating database backup..."
            docker compose exec -T db pg_dump -U $POSTGRES_USER $POSTGRES_DB > "$BACKUP_DIR/database.sql"
            
            echo "📁 Backing up media files..."
            cp -r watermarker/media "$BACKUP_DIR/"
            
            echo "📊 Backing up logs..."
            cp -r watermarker/logs "$BACKUP_DIR/"
            
            # Compress backup
            tar -czf "$BACKUP_DIR.tar.gz" "$BACKUP_DIR"
            rm -rf "$BACKUP_DIR"
            
            # Keep only last 7 days of backups
            find backups/ -name "prod_backup_*.tar.gz" -mtime +7 -delete
            
            echo "✅ Backup completed: $BACKUP_DIR.tar.gz"

  maintenance:
    runs-on: ubuntu-latest
    needs: backup
    steps:
      - name: System Maintenance
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/beb/PycharmProjects/watermarking
            
            echo "🧹 Performing system maintenance..."
            
            # Clean up Docker
            docker system prune -f
            docker volume prune -f
            
            # Clean up old log files
            find watermarker/logs/ -name "*.log" -mtime +30 -delete
            
            # Update system packages (if needed)
            sudo apt-get update && sudo apt-get upgrade -y
            
            # Restart services for fresh state
            docker compose restart
            
            echo "✅ Maintenance completed"
